### ISSUE TITLE
Moodle documentation for this plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [PawelSuwinski/moodle-qformat_simplecsv#1]
Congratulations on this plugin. It might just be what many teachers need to create many (text only) Multiple Choice Moodle questions extremely fast.

I hope you don't mind that I created a Moodle Docs page at
https://docs.moodle.org/36/en/qformat/simplecsv

I will be adding more to it later. You are wellcomed to add/remove/change as you see fit.

Maybe you can put a link to it in https://moodle.org/plugins/qformat_simplecsv

**Comment by PawelSuwinski** [comment]
I'm glad plugin  was found  useful :). Thanks for the docs page. Link added on plugin's page. 

Cheers.
